[colors]
ansi = [
  "#1F1F28",
  "#c84053",
  "#6f894e",
  "#77713f",
  "#4d699b",
  "#b35b79",
  "#597b75",
  "#545464",
]
brights = [
  "#8a8980",
  "#d7474b",
  "#6e915f",
  "#836f4a",
  "#6693bf",
  "#624c83",
  "#5e857a",
  "#43436c",
]

foreground = "#545464"
background = "#f2ecbc"

cursor_bg = "#43436c"
cursor_fg = "#43436c"
cursor_border = "#43436c"

selection_fg = "#43436c"
selection_bg = "#c9cbd1"

scrollbar_thumb = "#1F1F28"
split = "#1F1F28"

[colors.indexed]
16 = "#cc6d00"
17 = "#e82424"

[metadata]
name = 'Kanagawa Light'
