{ pkgs, packages, ... }: {
  home.packages = with pkgs;
    [
      alejandra
      amberol
      asciiquarium
      cmatrix
      dbeaver
      duf
      dynamic-wallpaper
      eartag
      easyeffects
      espeak
      exa
      eyedropper
      fd
      fragments
      glow
      gnome-extension-manager
      gnome-solanum
      gum
      htop
      httpie
      hyperfine
      insomnia
      lolcat
      lshw
      macchina
      mousai
      ncdu
      nixd
      nixfmt
      nixgl.nixGLIntel
      ripgrep
      screenkey
      sl
      speedtest-cli
      textpieces
      tldr
      tokei
      trash-cli
      unstable.obsidian
      unstable.yt-dlp
      wireshark
      wormhole-rs
      zellij
    ] ++ [ packages.hm-cleanup ];
}
