#!/bin/bash

# bspc monitor 'eDP-1' -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10'
$HOME/.config/bspwm/monitor.sh

bspc config 'border_width' '2'
bspc config 'borderless_monocle' 'on'
bspc config 'gapless_monocle' 'on'
bspc config 'split_ratio' '0.52'
bspc config 'window_gap' '12'
bspc config 'focus_follows_pointer' true
bspc config 'pointer_follows_focus' true
bspc config 'pointer_follows_monitor' true
bspc config 'normal_border_color' '#45475a'
bspc config 'focused_border_color' '#74c7ec'
bspc config 'presel_feedback_color' '#000000'

bspc rule -r '*'
# bspc rule -a 'Gimp' 'desktop=^8' 'follow=on' 'state=floating'
bspc rule -a 'Screenkey' 'manage=off'
bspc rule -a 'firefox-nightly' 'desktop=^1' 'state=tiled' 'follow=off'
bspc rule -a 'ncmpcpp' 'state=floating'
bspc rule -a 'Nitrogen' 'state=floating'
bspc rule -a 'avizo-service' 'state=floating'
bspc rule -a 'gnome-calculator' 'state=floating'

# java gui fixes
export _JAVA_AWT_WM_NONREPARENTING=1
bspc rule -a sun-awt-X11-XDialogPeer state=floating

kill $(pgrep -x sxhkd); sxhkd &
kill $(pgrep -x picom); picom &
# kill $(pgrep -x .avizo-service-); avizo-service &
pidof nm-applet || nm-applet --indicator &
nitrogen --restore
xset dpms 600 600 0
$HOME/.config/polybar/launch.sh
