format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$nix_shell\
$line_break\
$character
"""

[character]
error_symbol = "[>](red)"
success_symbol = "[>](purple)"
vimcmd_symbol = "[<](green)"

[cmd_duration]
format = "[$duration]($style) "

[directory]
style = "blue"
truncate_to_repo = true
truncation_length = 8

[fill]
symbol = " "

[git_branch]
format = "on [$branch(:$remote_branch)]($style) "
style = "bright-black"

[git_commit]
style = "bright-black"

[git_state]
style = "bright-black"

[git_status]
style = "bright-black"

[hostname]
format = "[$ssh_symbol$hostname]($style) in "

[shell]
disabled = false
style = "bright-black"

[username]
format = "[$user]($style)@"
