format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$nix_shell\
$cmd_duration\
$line_break\
$character
"""

add_newline = true

[character]
error_symbol = "[>](red)"
success_symbol = "[>](purple)"
vimcmd_symbol = "[<](green)"

[cmd_duration]
format = "[$duration]($style) "

[directory]
style = "blue"
truncation_length = 8
read_only = " "
format = "[$path]($style)[$read_only]($read_only_style) "

[fill]
symbol = " "

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_commit]
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](bright-black) ($ahead_behind$stashed)]($style) "
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[hostname]
format = "[$ssh_symbol$hostname]($style) in "

[nix_shell]
format = 'with [$symbol$state( \($name\))]($style) '
symbol = "❄️ "

[shell]
disabled = false
style = "bright-black"

[username]
format = "[$user]($style)@"
