#!/bin/bash

# format with easy align: gaip1 gaip2 gaip3 gaip4 gaip5 gaip6 gaip7 gaip8 gaip9 

# bspc monitor 'eDP-1' -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10'

bspc config 'border_width'            '2'
bspc config 'borderless_monocle'      'on'
bspc config 'gapless_monocle'         'on'
bspc config 'split_ratio'             '0.52'
bspc config 'window_gap'              '12'
bspc config 'focus_follows_pointer'   true
bspc config 'pointer_follows_focus'   true
bspc config 'pointer_follows_monitor' true
bspc config 'normal_border_color'     '#45475a'
bspc config 'focused_border_color'    '#74c7ec'
bspc config 'presel_feedback_color'   '#000000'
bspc config "external_rules_command"  "$HOME/.config/bspwm/external_rule.sh"

bspc rule -r '*'
bspc rule -a 'Screenkey' 'manage=off'

# java gui fixes
export _JAVA_AWT_WM_NONREPARENTING=1
bspc rule -a sun-awt-X11-XDialogPeer state=floating

_run_once() {
  pidof "$1" || "$@" &
}

# _kill_and_run() {
#   kill "$(pgrep -x "$@")"; "$@" &
# }

_kill_and_run() {
  kill "$(ps ax | grep "$1" | grep -v grep | awk '{print $1}')"; "$@" &
}

_kill_and_run sxhkd
_kill_and_run picom
_kill_and_run caffeine 
_kill_and_run dunst

_run_once nm-applet --indicator

nitrogen --restore
xset dpms 600 600 0
xob_server

"$HOME"/.config/polybar/launch.sh
"$HOME"/.config/bspwm/monitor.sh


