#!/bin/bash

# format with easy align: gaip1 gaip2 gaip3 gaip4 gaip5 gaip6 gaip7 gaip8 gaip9 

# bspc monitor 'eDP-1' -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10'
# bspc monitor 'HDMI-2' -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10'

INTERNAL_MONITOR="eDP1"
EXTERNAL_MONITOR="HDMI2"

# on first load setup default workspaces
if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
  bspc monitor "$EXTERNAL_MONITOR" -d 1 2 3 4 5
  bspc monitor "$INTERNAL_MONITOR" -d 6 7 8 9 10
  bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
else
  bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
fi

~/.config/bspwm/scripts/monitor.sh &
~/.config/polybar/launch.sh &

bspc config 'border_width'            '3'
bspc config 'borderless_monocle'      'on'
bspc config 'gapless_monocle'         'on'
bspc config 'split_ratio'             '0.52'
bspc config 'window_gap'              '10'
bspc config 'focus_follows_pointer'   true
bspc config 'pointer_follows_focus'   true
bspc config 'pointer_follows_monitor' true
bspc config 'normal_border_color'     '#575860'
bspc config 'focused_border_color'    '#719cd6'
bspc config 'presel_feedback_color'   '#000000'
bspc config "external_rules_command"  "$HOME/.config/bspwm/scripts/external_rule.sh"

bspc rule -r '*'
bspc rule -a 'Screenkey' 'manage=off'

# java gui fixes
export _JAVA_AWT_WM_NONREPARENTING=1
bspc rule -a sun-awt-X11-XDialogPeer state=floating

_run_once() {
  pidof "$1" || "$@" &
}

# _kill_and_run() {
#   kill "$(pgrep -x "$@")"; "$@" &
# }

_kill_and_run() {
  kill "$(ps ax | grep "$1" | grep -v grep | awk '{print $1}')"; "$@" &
}

_kill_and_run sxhkd -c ~/.config/sxhkd/sxhkdrc.bspwm ~/.config/sxhkd/sxhkdrc.common
_kill_and_run wrapped_picom
_kill_and_run dunst

_run_once nm-applet --indicator
_run_once caffeine start

nitrogen --restore
xset dpms 600 600 0
xob_server &
rfkill block bluetooth

pgrep bspswallow.sh || ~/.config/bspwm/scripts/bspswallow.sh &
pgrep xfce-polkit || /usr/libexec/xfce-polkit &
