# $rosewater #f5e0dc
# $flamingo  #f2cdcd
# $pink      #f5c2e7
# $mauve     #cba6f7
# $red       #f38ba8
# $maroon    #eba0ac
# $peach     #fab387
# $green     #a6e3a1
# $teal      #94e2d5
# $sky       #89dceb
# $sapphire  #74c7ec
# $blue      #89b4fa
# $lavender  #b4befe
# $text      #cdd6f4
# $subtext1  #bac2de
# $subtext0  #a6adc8
# $overlay2  #9399b2
# $overlay1  #7f849c
# $overlay0  #6c7086
# $surface2  #585b70
# $surface1  #45475a
# $surface0  #313244
# $base      #1e1e2e
# $mantle    #181825
# $crust     #11111b
# idle_bg = ""
# idle_fg = ""
# info_bg = ""
# info_fg = ""
# good_bg = ""
# good_fg = ""
# warning_bg = ""
# warning_fg = ""
# critical_bg = ""
# critical_fg = ""
# idle_bg = ""

idle_fg = "#CDD6F4"
# info_bg = "#89B4FA"
info_fg = "#89B4FA"
# good_bg = "#A6E3A1"
good_fg = "#A6E3A1"
# warning_bg = "#FAB387"
warning_fg = "#FAB387"
critical_bg = "#F38BA8"
critical_fg = "#1E1E2E"

# separator = "\ue0b6"
separator_bg = "auto"
separator_fg = "auto"
