# idle_bg = "#1E1E2E"
# idle_fg = "#CDD6F4"
# info_bg = "#89B4FA"
# info_fg = "#1E1E2E"
# good_bg = "#A6E3A1"
# good_fg = "#1E1E2E"
# warning_bg = "#FAB387"
# warning_fg = "#1E1E2E"
# critical_bg = "#F38BA8"
# critical_fg = "#1E1E2E"
# idle_bg = "#1E1E2E"
idle_fg = "#CDD6F4"
# info_bg = "#89B4FA"
info_fg = "#89B4FA"
# good_bg = "#A6E3A1"
good_fg = "#A6E3A1"
# warning_bg = "#FAB387"
warning_fg = "#FAB387"
critical_bg = "#F38BA8"
critical_fg = "#1E1E2E"
# separator = "\ue0b6"
separator_bg = "auto"
separator_fg = "auto"
