icons_format = "{icon}"

[theme]
theme = "roso"

[icons]
icons = "material-nf"

[[block]]
block = "cpu"
interval = 1
format = "[ CPU $utilization ]"
format_alt = "[ CPU $utilization $barchart ]"
[block.theme_overrides]
idle_fg = "#f5e0dc"

[[block]]
block = "memory"
interval = 1
format = "[ RAM $mem_used/$mem_total ]"
format_alt = "[ SWAP $swap_used/$swap_total ]"
[block.theme_overrides]
idle_fg = "#f2cdcd"

[[block]]
block = "net"
format = "[ Connected to {$ssid|Wired connection} ]"
format_alt = "[ Connected to {$ssid|Wired connection} ↑$speed_up ↓$speed_down ]"
inactive_format = "[ Internet Disconnected ]"
missing_format = "[ Missing connection ]"
[block.theme_overrides]
idle_fg = "#f5c2e7"

[[block]]
block = "sound"
format = "[ Volume {$volume|muted} ]"
show_volume_when_muted = false
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.theme_overrides]
idle_fg = "#eba0ac"

[[block]]
block = "backlight"
invert_icons = false
format = "[ Brightness $brightness ]"
[block.theme_overrides]
idle_fg = "#fab387"

[[block]]
block = "battery"
format = "[ Battery at $percentage ] [ using $power ] [ $time battery time ]"
full_format = "[ Battery full at $percentage ]"
charging_format = "[ Battery charging at $percentage ] [ using $power ] [ $time battery time ]"
not_charging_format = "[ Battery discharging at $percentage ] [ using $power ] [ $time battery time ]"
missing_format = "[ No battery found ]"
empty_format = "[ Battery empty ]"

[[block]]
block = "time"
interval = 5
format = "[ $timestamp.datetime(f:'%a %d') · $timestamp.datetime(f:'%R') ]"
[block.theme_overrides]
idle_fg = "#b4befe"
